
GET http://localhost:3001/some.text/

GET http://localhost:3001/post/

GET http://localhost:3001/posts/

GET http://localhost:3001/tag/

GET http://localhost:3001/tags/

GET http://localhost:3001/tagsssssssssssss/

GET http://localhost:3001/error/404

GET http://localhost:3001/error/404

GET http://localhost:3001/drangonfly

GET http://localhost:3001/fly

GET http://localhost:3001/flybird



